### ISSUE TITLE
Waterfall rules - feature

### ISSUE THREAD

**Issue by OrestF** [coaxsoft/passpartu#10]
Add configurable feature - `waterfall_rules`

If policy rule is missed, but the key above value equals `true` - positive policy (true)
It must work with any number of keys!

Example
```
admin:
  <<: *manager
  post:
    create: false
    update: true
    delete: true 
  order: true
```

`admin_user.can?(:order, :create) # true`
`admin_user.can?(:order, :update) # true`
`admin_user.can?(:order, :whatever) # true`
